In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = 'C:\cs\data science\depi\house_file.csv'

df = pd.read_csv(url)

In [3]:
print("dublicated data")
print(df.duplicated().sum())

dublicated data
5

In [4]:
df.drop_duplicates()

,URL,Type,Size,Levels,Garage,Taxes,MLS Number,Price,address,garage,bedroom,bathroom,date released
0,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,1700 sqft,Residential,No,"$9,253",R2948263,"$2,589,800","2354 Burquitlam Dr, Vancouver, British Columbia",4,3,1,1953.0
1,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1046 sqft,Residential,Yes,"$4,110",R2945354,"$1,249,000","3008 - 1033 Marinaside Cres, Vancouver, Briti...",0,2,2,2001.0
2,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,498 sqft,Residential,Yes,"$1,262",R2946140,"$420,000","705 - 150 E Cordova St, Vancouver, British Co...",0,1,1,2016.0
3,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,1923 sqft,Residential,Yes,"$8,488",R2945519,"$2,999,000","5142 Killarney St, Vancouver, British Columbia",2,5,4,2010.0
4,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,788 sqft,Residential,Yes,NaN,R2944675,"$901,900","319 - 8633 River District Cross, Vancouver, B...",1,2,2,2028.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1493 sqft,Residential,Yes,"$6,871",R2903167,"$2,980,000","2603 - 1205 W Hastings St, Vancouver, British...",2,2,2,2007.0
955,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1278 sqft,Residential,Yes,"$4,307",R2919195,"$1,636,000","306 - 4759 Valley Dr, Vancouver, British Colu...",1,2,2,2005.0
956,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,8655 sqft,Residential,Yes,"$38,548",R2902208,"$9,980,000","6836 Arbutus St, Vancouver, British Columbia",3,8,9,2019.0
957,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,833 sqft,Residential,Yes,"$2,680",R2898935,"$899,900","2206 - 3538 Sawmill Cres, Vancouver, British ...",1,2,2,2022.0
958,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,600 sqft,Residential,Yes,"$1,935",R2919946,"$618,800","308 - 5058 Joyce St, Vancouver, British Columbia",0,1,1,2021.0

In [5]:
print(df.isna().sum())
df.info()

URL                0
Type              15
Size               0
Levels             0
Garage             0
Taxes            140
MLS Number         0
Price              1
address           17
garage             0
bedroom            0
bathroom           0
date released     10
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 959 entries, 0 to 958
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   URL            959 non-null    object
 1   Type           944 non-null    object
 2   Size           959 non-null    object
 3   Levels         959 non-null    object
 4   Garage         959 non-null    object
 5   Taxes          819 non-null    object
 6   MLS Number     959 non-null    object
 7   Price          958 non-null    object
 8   address        942 non-null    object
 9   garage         959 non-null    int64
 10  bedroom        959 non-null    int64
 11  bathroom       959 non-null    int64
 12  date released  949 non-null    float64
dtypes: float64(1), int64(3), object(9)
memory usage: 97.5+ KB

In [6]:
#to remove sqrft and convert to numeric 
df["Size"] = df['Size'].str.replace("sqft","",regex=False)
df['Size'] = pd.to_numeric(df['Size'],errors="coerce")

In [7]:
df['Taxes'] = df['Taxes'].str.replace("$","",regex=False)
df['Taxes'] = df['Taxes'].str.replace(",",".").astype(float)
df['Taxes']

0       9.253
1       4.110
2       1.262
3       8.488
4         NaN
        ...
954     6.871
955     4.307
956    38.548
957     2.680
958     1.935
Name: Taxes, Length: 959, dtype: float64

In [8]:
df['Price'] = df['Price'].str.replace("$","")
df['Price'] = df['Price'].str.replace(",","")
df['Price'] = df['Price'].replace({'X': None})
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [9]:
df['age'] = 2025 - df['date released']
df['age'] = df['age'].apply(lambda x: x if x >= 0 else 0)

df['age']

0      72.0
1      24.0
2       9.0
3      15.0
4       0.0
       ...
954    18.0
955    20.0
956     6.0
957     3.0
958     4.0
Name: age, Length: 959, dtype: float64

In [10]:
df.isna().sum()

URL                0
Type              15
Size               7
Levels             0
Garage             0
Taxes            140
MLS Number         0
Price             17
address           17
garage             0
bedroom            0
bathroom           0
date released     10
age                0
dtype: int64

In [11]:
rows_with_more_than_3_nulls = df[df.isnull().sum(axis=1) > 3]

print(rows_with_more_than_3_nulls)

df = df.dropna(thresh=df.shape[1] - 3)

                                                   URL Type    Size  \
235  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN     NaN
393  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN  1075.0
530  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN  1678.0
534  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN  2000.0
622  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN     NaN
740  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN  2340.0
784  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN   828.0
884  https://www.zoocasa.com/vancouver-bc-real-esta...  NaN   672.0

                   Levels Garage   Taxes MLS Number  Price address  garage  \
235       Commercial Sale     No     NaN   C8064539    NaN     NaN       0
393  Business Opportunity     No     NaN   C8063483    NaN     NaN       0
530  Business Opportunity     No     NaN   C8063475    NaN     NaN       0
534  Business Opportunity     No     NaN   C8063446    NaN     NaN       0
622                  Land     No  24.672   C8062640    NaN     NaN       0
740  Business Opportunity     No     NaN   C8062706    NaN     NaN       0
784  Business Opportunity     No     NaN   C8061124    NaN     NaN       0
884  Business Opportunity     No     NaN   C8062554    NaN     NaN       0

     bedroom  bathroom  date released   age
235        0         0            NaN   0.0
393        0         0         1949.0  76.0
530        0         0            NaN   0.0
534        0         0            NaN   0.0
622        0         0            NaN   0.0
740        0         0            NaN   0.0
784        0         0            NaN   0.0
884        0         0            NaN   0.0

In [12]:
df.isna().sum()

URL                0
Type               7
Size               5
Levels             0
Garage             0
Taxes            133
MLS Number         0
Price              9
address            9
garage             0
bedroom            0
bathroom           0
date released      3
age                0
dtype: int64

In [13]:
df.loc[:,'Size'] = df['Size'].fillna(df['Size'].median())
df.loc[:,'Price'] = df['Price'].fillna(df['Price'].median())
df.loc[:, 'date released'] = df['date released'].fillna(df['date released'].median())

In [14]:
most_frequent = df['Type'].mode()[0]
df['Type'] = df['Type'].fillna(most_frequent)

most_frequent_addr = df['address'].mode()[0]
df['address'] = df['address'].fillna(most_frequent_addr)

In [15]:
df["Taxes"] = df['Taxes'].fillna(df['Taxes'].median())

In [16]:
df.isna().sum()

URL              0
Type             0
Size             0
Levels           0
Garage           0
Taxes            0
MLS Number       0
Price            0
address          0
garage           0
bedroom          0
bathroom         0
date released    0
age              0
dtype: int64

In [17]:
df.describe()

,Size,Taxes,Price,garage,bedroom,bathroom,date released,age
count,951.000000,951.000000,9.510000e+02,951.000000,951.000000,951.000000,951.000000,951.000000
mean,1585.293901,8.714992,2.132013e+06,1.483701,2.742376,2.162986,2028.582545,26.309148
std,1380.657773,33.208085,2.615594e+06,1.634979,1.835866,1.312987,467.322676,29.638544
min,147.000000,0.282100,9.900000e+04,0.000000,0.000000,0.000000,1905.000000,0.000000
25%,732.000000,2.288000,7.994000e+05,1.000000,1.000000,1.000000,1992.000000,4.000000
50%,1176.500000,3.715500,1.475000e+06,1.000000,2.000000,2.000000,2008.000000,17.000000
75%,1928.500000,7.129000,2.370500e+06,2.000000,4.000000,3.000000,2020.000000,33.000000
max,20629.000000,761.000000,3.200000e+07,27.000000,11.000000,9.000000,9999.000000,120.000000

,URL,Type,Size,Levels,Garage,Taxes,MLS Number,Price,address,garage,bedroom,bathroom,date released,age
0,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,1700.0,Residential,No,9.2530,R2948263,2589800.0,"2354 Burquitlam Dr, Vancouver, British Columbia",4,3,1,1953.0,72.0
1,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1046.0,Residential,Yes,4.1100,R2945354,1249000.0,"3008 - 1033 Marinaside Cres, Vancouver, Briti...",0,2,2,2001.0,24.0
2,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,498.0,Residential,Yes,1.2620,R2946140,420000.0,"705 - 150 E Cordova St, Vancouver, British Co...",0,1,1,2016.0,9.0
3,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,1923.0,Residential,Yes,8.4880,R2945519,2999000.0,"5142 Killarney St, Vancouver, British Columbia",2,5,4,2010.0,15.0
4,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,788.0,Residential,Yes,3.7155,R2944675,901900.0,"319 - 8633 River District Cross, Vancouver, B...",1,2,2,2028.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1493.0,Residential,Yes,6.8710,R2903167,2980000.0,"2603 - 1205 W Hastings St, Vancouver, British...",2,2,2,2007.0,18.0
955,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,1278.0,Residential,Yes,4.3070,R2919195,1636000.0,"306 - 4759 Valley Dr, Vancouver, British Colu...",1,2,2,2005.0,20.0
956,https://www.zoocasa.com/vancouver-bc-real-esta...,Single Family Residence,8655.0,Residential,Yes,38.5480,R2902208,9980000.0,"6836 Arbutus St, Vancouver, British Columbia",3,8,9,2019.0,6.0
957,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,833.0,Residential,Yes,2.6800,R2898935,899900.0,"2206 - 3538 Sawmill Cres, Vancouver, British ...",1,2,2,2022.0,3.0
958,https://www.zoocasa.com/vancouver-bc-real-esta...,Apartment/Condominium,600.0,Residential,Yes,1.9350,R2919946,618800.0,"308 - 5058 Joyce St, Vancouver, British Columbia",0,1,1,2021.0,4.0